### ISSUE TITLE
Could not find library corresponding to plugin nodelets_os/OusterSensor

### ISSUE THREAD

**Issue by wert93** [ouster-lidar/ouster-ros#72] opened 2023-03-01 16:09 UTC
I have just installed the latest version of the Ouster drivers for my Ouster OS1-128-U. I am on Ubuntu 20.04 and ROS noetic.

When launching:

`roslaunch ouster_ros sensor.launch sensor_hostname:=169.254.155.163`

I get:

```
... logging to /home/caboto/.ros/log/ac46741a-b84a-11ed-be3c-e343bacb489b/roslaunch-caboto-NUC12WSHi7-5213.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://caboto-NUC12WSHi7:39171/

SUMMARY
========

PARAMETERS
 * /ouster/os_cloud_node/tf_prefix: 
 * /ouster/os_cloud_node/timestamp_mode: 
 * /ouster/os_node/imu_port: 0
 * /ouster/os_node/lidar_mode: 
 * /ouster/os_node/lidar_port: 0
 * /ouster/os_node/metadata: 
 * /ouster/os_node/sensor_hostname: 169.254.155.163
 * /ouster/os_node/timestamp_mode: 
 * /ouster/os_node/udp_dest: 
 * /ouster/os_node/udp_profile_lidar: 
 * /rosdistro: noetic
 * /rosversion: 1.15.15

NODES
  /
    relay_imu (topic_tools/relay)
    relay_lidar (topic_tools/relay)
    rviz (rviz/rviz)
  /ouster/
    img_node (nodelet/nodelet)
    os_cloud_node (nodelet/nodelet)
    os_node (nodelet/nodelet)
    os_nodelet_mgr (nodelet/nodelet)

auto-starting new master
process[master]: started with pid [5221]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to ac46741a-b84a-11ed-be3c-e343bacb489b
process[rosout-1]: started with pid [5231]
started core service [/rosout]
process[ouster/os_nodelet_mgr-2]: started with pid [5238]
process[ouster/os_node-3]: started with pid [5240]
process[ouster/os_cloud_node-4]: started with pid [5242]
process[ouster/img_node-5]: started with pid [5244]
process[rviz-6]: started with pid [5246]
process[relay_lidar-7]: started with pid [5248]
process[relay_imu-8]: started with pid [5249]
[ INFO] [1677686639.964743613]: Initializing nodelet with 16 worker threads.
[ INFO] [1677686640.961316012]: Loading nodelet /ouster/os_node of type nodelets_os/OusterSensor to manager os_nodelet_mgr with the following remappings:
[ERROR] [1677686640.970765523]: Failed to load nodelet [/ouster/os_node] of type [nodelets_os/OusterSensor] even after refreshing the cache: Could not find library corresponding to plugin nodelets_os/OusterSensor. Make sure the plugin description XML file has the correct name of the library and that the library actually exists.
[ERROR] [1677686640.970779217]: The error before refreshing the cache was: Could not find library corresponding to plugin nodelets_os/OusterSensor. Make sure the plugin description XML file has the correct name of the library and that the library actually exists.
[FATAL] [1677686640.970998411]: Failed to load nodelet '/ouster/os_node` of type `nodelets_os/OusterSensor` to manager `os_nodelet_mgr'
================================================================================REQUIRED process [ouster/os_node-3] has died!
process has died [pid 5240, exit code 255, cmd bash -c sleep 3; $0 $@ /opt/ros/noetic/lib/nodelet/nodelet load nodelets_os/OusterSensor os_nodelet_mgr __name:=os_node __log:=/home/caboto/.ros/log/ac46741a-b84a-11ed-be3c-e343bacb489b/ouster-os_node-3.log].
log file: /home/caboto/.ros/log/ac46741a-b84a-11ed-be3c-e343bacb489b/ouster-os_node-3*.log
Initiating shutdown!
================================================================================
[relay_imu-8] killing on exit
[relay_lidar-7] killing on exit
[rviz-6] killing on exit
[ouster/os_cloud_node-4] killing on exit
[ouster/os_nodelet_mgr-2] killing on exit
[ouster/os_node-3] killing on exit
[ouster/img_node-5] killing on exit
[rosout-1] killing on exit
[master] killing on exit
shutting down processing monitor...
... shutting down processing monitor complete
done
```

**Comment by Samahu** [comment] 2023-03-01 17:00
Checking your roslaunch I couldn't identify the cause of the problem, why your roslaunch failed to load the os_nodelet?

- Did you a clean build of the workspace? Can you include your clean build log?
- Did you source the catkin workspace `devel/setup.bash` after the project successfully compiled?

**Comment by AchmadFathoni** [comment] 2023-03-07 10:03
@Samahu I have same error, here is my environment

- OS: Debian GNU/Linux 10 (buster) aarch64
- Host: Raspberry Pi 4 Model B Rev 1.1
- ROS: Noetic

LIDAR version
```
{
  "prod_line": "OS-1-32-U1",
  "prod_pn": "840-102145-D",
  "prod_sn": "122104000126",
  "image_rev": "ousteros-image-prod-aries-v2.4.0+20220921174636",
  "build_rev": "v2.4.0",
  "build_date": "2022-09-21T17:47:45Z",
  "status": "RUNNING",
  "initialization_id": 2573177
}
```

Error message from debug build
```
[ERROR] [1678182983.716857980]: Failed to load nodelet [/ouster/os_node] of type [nodelets_os/OusterSensor] even after refreshing the cache: MultiLibraryClassLoader: Could not create object of class type nodelets_os::OusterSensor as no factory exists for it. Make sure that the library exists and was explicitly loaded through MultiLibraryClassLoader::loadLibrary()
[ERROR] [1678182983.716984684]: The error before refreshing the cache was: Failed to load library /home/pi/catkin_ws/devel/lib//libnodelets_os.so. Make sure that you are calling the PLUGINLIB_EXPORT_CLASS macro in the library code, and that names are consistent between this macro and your XML. Error string: Could not load library (Poco exception = /usr/lib/aarch64-linux-gnu/libGLdispatch.so.0: cannot allocate memory in static TLS block)
[FATAL] [1678182983.717398832]: Failed to load nodelet '/ouster/os_node` of type `nodelets_os/OusterSensor` to manager `os_nodelet_mgr'
[ERROR] [1678182983.737748887]: Failed to load nodelet [/ouster/os_cloud_node] of type [nodelets_os/OusterCloud] even after refreshing the cache: MultiLibraryClassLoader: Could not create object of class type nodelets_os::OusterCloud as no factory exists for it. Make sure that the library exists and was explicitly loaded through MultiLibraryClassLoader::loadLibrary()
[ERROR] [1678182983.737863906]: The error before refreshing the cache was: MultiLibraryClassLoader: Could not create object of class type nodelets_os::OusterCloud as no factory exists for it. Make sure that the library exists and was explicitly loaded through MultiLibraryClassLoader::loadLibrary()
[FATAL] [1678182983.738274276]: Failed to load nodelet '/ouster/os_cloud_node` of type `nodelets_os/OusterCloud` to manager `os_nodelet_mgr'
[ERROR] [1678182983.757132887]: Failed to load nodelet [/ouster/img_node] of type [nodelets_os/OusterImage] even after refreshing the cache: MultiLibraryClassLoader: Could not create object of class type nodelets_os::OusterImage as no factory exists for it. Make sure that the library exists and was explicitly loaded through MultiLibraryClassLoader::loadLibrary()
[ERROR] [1678182983.757542739]: The error before refreshing the cache was: MultiLibraryClassLoader: Could not create object of class type nodelets_os::OusterImage as no factory exists for it. Make sure that the library exists and was explicitly loaded through MultiLibraryClassLoader::loadLibrary()
[FATAL] [1678182983.758036350]: Failed to load nodelet '/ouster/img_node` of type `nodelets_os/OusterImage` to manager `os_nodelet_mgr'

```

**Comment by AchmadFathoni** [comment] 2023-03-07 10:31
My problem seems to be solver by executing `export LD_PRELOAD=/usr/lib/aarch64-linux-gnu/libGLdispatch.so.0:$LD_PRELOAD`. [Source](https://forums.developer.nvidia.com/t/lib-aarch64-linux-gnu-libgldispatch-so-0-cannot-allocate-memory-in-static-tls-block/235466/3)

**Comment by Samahu** [comment] 2023-04-07 18:58
@wert93 Have you tried the solution that @AchmadFathoni suggested?

In any case, I am going to close this issue since I couldn't re-produce and there was no further responses that I could provide based on available info.

**Closed by Samahu** 2023-04-07 18:58 UTC

**Comment by L-Reichardt** [comment] 2023-07-24 08:11
For reference: When I faced this issue, the cause was an incorrect catkin_make installation. Exporting libGLdispatch.so had no effect.

**Comment by Samahu** [comment] 2023-07-24 17:19
> For future reference: When I faced this issue, the cause was an incorrect catkin_make installation. Exporting libGLdispatch.so had no effect.

So users have to re-install **catkin_make** for this to work properly?

**Comment by Vineet-Pandey** [comment] 2023-08-16 15:46
Has a solution been arrived for this issue? Because this seems to be commonly occurring issue.

**Comment by Samahu** [comment] 2023-08-16 16:44
Thanks for sharing the info. Since I mainly tasked with the **ouster_ros** package itself I don't run into this issue, and as such I  don't know what it takes to address the issue when cloning+combining the driver into existing ros workspaces. Some times it is necessary to perform a clean-rebuild for the ROS workspace to get over issues like this.
