### ISSUE TITLE
Ouster os1 crashes in ros environment.

### ISSUE THREAD

**Issue by rupikaraj** [ouster-lidar/ouster-ros#126] opened 2023-05-08 05:35 UTC
**Describe your question**
I am facing an issue while trying to launch ouster-os1 lidar from melodic ros environment. I have given below the screenshots of error. 

Kindly help me to sort out the issue.
Thank in advance.

**Platform**
- Ouster Sensor  OS-1
- ROS version Melodic
- Operating System : Linux

![Screenshot from 2023-05-08 11-00-10](https://user-images.githubusercontent.com/105413461/236742138-811cb4d8-aa46-4ebf-b2dd-3c704d5fe901.png)
![Screenshot from 2023-05-08 11-01-00](https://user-images.githubusercontent.com/105413461/236742167-33ed97c4-ef34-4890-9c2c-33dfa59838fb.png)

**Comment by Samahu** [comment] 2023-05-08 14:57
The driver is complaining that it can't resolve the hostname of the sensor, are you able to ping the device using the hostname form the machine that you are running on? try to see if you using the IP address works rather than the hostname?

**Comment by Samahu** [comment] 2023-05-10 12:07
@rupikaraj the problem is unlikely code related. For this type of issues you would get better assistance through [Ouster Customer Support](https://ouster.atlassian.net/servicedesk/customer/portal/8/group/47/create/170), Closing the issue.

**Closed by Samahu** 2023-05-10 12:07 UTC
Labels: question
